version: '3'

services:
    redis-server:
        image: 'redis'
        
    app:
        build: .
        ports: 
            - "4004:4444" #the first part is the public port on docker sent from browser while the last part is the original port from code
        restart: always
        depends_on:
            - 'redis-server'